name: CI/CD to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🧪 Linter et tests frontend (optionnel)
        run: |
          cd frontend
          npm ci
          npm run lint
          npm test

      - name: 🧪 Linter et tests backend (optionnel)
        run: |
          cd backend
          npm ci
          npm run lint
          npm test

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🔑 Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 🏗️ Build & push frontend image
        run: |
          docker build -t ${{ secrets.ECR_FRONTEND_REPO }}:$IMAGE_TAG ./frontend
          docker push ${{ secrets.ECR_FRONTEND_REPO }}:$IMAGE_TAG

      - name: 🏗️ Build & push backend image
        run: |
          docker build -t ${{ secrets.ECR_BACKEND_REPO }}:$IMAGE_TAG ./backend
          docker push ${{ secrets.ECR_BACKEND_REPO }}:$IMAGE_TAG
